### PR TITLE
Add Windows functionality

### PR DESCRIPTION
**Pull request by OlivierBinette**
Here's a proposal for added Windows functionality and behaviour which is closer to the usual "replicate" function. I also made a few changes to the readme and documentation - these could be reverted or ajusted if needed.

### CODE REVIEW

**Comment by christophergandrud** [comment]
Thanks for the contribution! I've merge it in and will upload to CRAN.

**Comment by christophergandrud** [comment]
@OlivierBinette and @Autumn41  I don't have access to a Windows machine. If possible could you test out the most recent version of `mc_replicate` on GitHub to see how well it works for you?

**Comment by OlivierBinette** [comment]
@christophergandrud I'll test it and come back to you.

**Comment by OlivierBinette** [comment]
Package passes all `devtools::check_win_*` checks on win-builder.r-project.org. Only note is:
```
* checking LazyData ... NOTE
  'LazyData' is specified without a 'data' directory
```

**Comment by christophergandrud** [comment]
Thanks @OlivierBinette pushed to CRAN now

**Pull request merged**
